/*
 * This file is generated by jOOQ.
*/
package com.zemrow.test.dsl.jooq.autogen.auth;


import com.zemrow.test.dsl.jooq.autogen.MainConst;
import com.zemrow.test.dsl.jooq.autogen.auth.dao.constants.AuthEntryPointConst;
import com.zemrow.test.dsl.jooq.autogen.auth.dao.constants.AuthSessionConst;
import com.zemrow.test.dsl.jooq.autogen.auth.dao.constants.AuthSessionFailConst;
import com.zemrow.test.dsl.jooq.autogen.auth.dao.constants.AuthUserConst;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class SchemaAuthConst extends SchemaImpl {

    private static final long serialVersionUID = 1282645452;

    /**
     * The reference instance of <code>auth</code>
     */
    public static final SchemaAuthConst AUTH = new SchemaAuthConst();

    /**
     * Способы авторизации пользователя
     */
    public final AuthEntryPointConst AUTH_ENTRY_POINT = com.zemrow.test.dsl.jooq.autogen.auth.dao.constants.AuthEntryPointConst.AUTH_ENTRY_POINT;

    /**
     * Сессия пользователя
     */
    public final AuthSessionConst AUTH_SESSION = com.zemrow.test.dsl.jooq.autogen.auth.dao.constants.AuthSessionConst.AUTH_SESSION;

    /**
     * Неудачные попытки войти в систему
     */
    public final AuthSessionFailConst AUTH_SESSION_FAIL = com.zemrow.test.dsl.jooq.autogen.auth.dao.constants.AuthSessionFailConst.AUTH_SESSION_FAIL;

    /**
     * Пользователь
     */
    public final AuthUserConst AUTH_USER = com.zemrow.test.dsl.jooq.autogen.auth.dao.constants.AuthUserConst.AUTH_USER;

    /**
     * No further instances allowed
     */
    private SchemaAuthConst() {
        super("auth", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return MainConst.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
                AuthEntryPointConst.AUTH_ENTRY_POINT,
                AuthSessionConst.AUTH_SESSION,
                AuthSessionFailConst.AUTH_SESSION_FAIL,
                AuthUserConst.AUTH_USER);
    }
}
