/*
 * This file is generated by jOOQ.
*/
package com.zemrow.test.dsl.jooq.autogen.log;


import com.zemrow.test.dsl.jooq.autogen.MainConst;
import com.zemrow.test.dsl.jooq.autogen.log.dao.constants.RoutLogConst;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class SchemaLogConst extends SchemaImpl {

    private static final long serialVersionUID = -923971069;

    /**
     * The reference instance of <code>log</code>
     */
    public static final SchemaLogConst LOG = new SchemaLogConst();

    /**
     * Логи вызовов сервисов
     */
    public final RoutLogConst ROUT_LOG = com.zemrow.test.dsl.jooq.autogen.log.dao.constants.RoutLogConst.ROUT_LOG;

    /**
     * No further instances allowed
     */
    private SchemaLogConst() {
        super("log", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return MainConst.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
                RoutLogConst.ROUT_LOG);
    }
}
