/*
 * This file is generated by jOOQ.
*/
package com.zemrow.test.dsl.jooq.autogen.auth.dao.entity;


import com.zemrow.test.dsl.jooq.impl.AbstractEntity;

import java.io.Serializable;
import java.util.UUID;


/**
 * Пользователь
 */
public class AuthUserEntity extends AbstractEntity implements Serializable {

    private static final long serialVersionUID = -1476540156;

    /**
     * Состояние пользователя: Не в сети, В сети, Не беспокоить
     */
    private String label;
    /**
     * Дата создания записи
     */
    private Long createTime;
    /**
     * Пользователь создавший запись
     */
    private UUID createdBy;
    /**
     * Дата обновления записи
     */
    private Long updateTime;
    /**
     * Пользователь обновивший запись
     */
    private UUID updatedBy;
    /**
     * Дата удаления записи
     */
    private Long deleteTime;
    /**
     * Пользователь удаливший запись
     */
    private UUID deletedBy;

    public AuthUserEntity() {
    }

    public AuthUserEntity(AuthUserEntity value) {
        super(value);
        this.label = value.label;
        this.createTime = value.createTime;
        this.createdBy = value.createdBy;
        this.updateTime = value.updateTime;
        this.updatedBy = value.updatedBy;
        this.deleteTime = value.deleteTime;
        this.deletedBy = value.deletedBy;
    }

    public AuthUserEntity(
            UUID id,
            String label,
            Long createTime,
            UUID createdBy,
            Long updateTime,
            UUID updatedBy,
            Long deleteTime,
            UUID deletedBy
    ) {
        super(id);
        this.label = label;
        this.createTime = createTime;
        this.createdBy = createdBy;
        this.updateTime = updateTime;
        this.updatedBy = updatedBy;
        this.deleteTime = deleteTime;
        this.deletedBy = deletedBy;
    }

    public String getLabel() {
        return this.label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    public Long getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public UUID getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(UUID createdBy) {
        this.createdBy = createdBy;
    }

    public Long getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    public UUID getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(UUID updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Long getDeleteTime() {
        return this.deleteTime;
    }

    public void setDeleteTime(Long deleteTime) {
        this.deleteTime = deleteTime;
    }

    public UUID getDeletedBy() {
        return this.deletedBy;
    }

    public void setDeletedBy(UUID deletedBy) {
        this.deletedBy = deletedBy;
    }

    @Override
    public String toString() {
        final StringBuilder sb = new StringBuilder("AuthUserEntity (");

        sb.append("id:").append(id);
        sb.append(", label:").append(label);
        sb.append(", createTime:").append(createTime);
        sb.append(", createdBy:").append(createdBy);
        sb.append(", updateTime:").append(updateTime);
        sb.append(", updatedBy:").append(updatedBy);
        sb.append(", deleteTime:").append(deleteTime);
        sb.append(", deletedBy:").append(deletedBy);

        sb.append(")");
        return sb.toString();
    }

    @Override
    public boolean equals(Object obj) {
        if (!super.equals(obj)) {
            return false;
        }
        if (!(obj instanceof AuthUserEntity)) {
            return false;
        }
        final AuthUserEntity other = (AuthUserEntity) obj;
        if (label == null) {
            if (other.label != null) {
                return false;
            }
        } else if (!label.equals(other.label)) {
            return false;
        }
        if (createTime == null) {
            if (other.createTime != null) {
                return false;
            }
        } else if (!createTime.equals(other.createTime)) {
            return false;
        }
        if (createdBy == null) {
            if (other.createdBy != null) {
                return false;
            }
        } else if (!createdBy.equals(other.createdBy)) {
            return false;
        }
        if (updateTime == null) {
            if (other.updateTime != null) {
                return false;
            }
        } else if (!updateTime.equals(other.updateTime)) {
            return false;
        }
        if (updatedBy == null) {
            if (other.updatedBy != null) {
                return false;
            }
        } else if (!updatedBy.equals(other.updatedBy)) {
            return false;
        }
        if (deleteTime == null) {
            if (other.deleteTime != null) {
                return false;
            }
        } else if (!deleteTime.equals(other.deleteTime)) {
            return false;
        }
        if (deletedBy == null) {
            if (other.deletedBy != null) {
                return false;
            }
        } else if (!deletedBy.equals(other.deletedBy)) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int result = super.hashCode();
        result = 31 * result + ((label == null) ? 0 : label.hashCode());
        result = 31 * result + ((createTime == null) ? 0 : createTime.hashCode());
        result = 31 * result + ((createdBy == null) ? 0 : createdBy.hashCode());
        result = 31 * result + ((updateTime == null) ? 0 : updateTime.hashCode());
        result = 31 * result + ((updatedBy == null) ? 0 : updatedBy.hashCode());
        result = 31 * result + ((deleteTime == null) ? 0 : deleteTime.hashCode());
        result = 31 * result + ((deletedBy == null) ? 0 : deletedBy.hashCode());
        return result;
    }
}
