/*
 * This file is generated by jOOQ.
*/
package com.zemrow.test.dsl.jooq.autogen.auth.dao.entity;


import java.io.Serializable;
import java.util.UUID;


/**
 * Неудачные попытки войти в систему
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class AuthSessionFailEntity implements Serializable {

    private static final long serialVersionUID = 1876681733;

    private UUID id;
    private UUID authEntryPointId;
    private String ipAddress;
    private String comment;
    private Long createTime;

    public AuthSessionFailEntity() {
    }

    public AuthSessionFailEntity(AuthSessionFailEntity value) {
        this.id = value.id;
        this.authEntryPointId = value.authEntryPointId;
        this.ipAddress = value.ipAddress;
        this.comment = value.comment;
        this.createTime = value.createTime;
    }

    public AuthSessionFailEntity(
            UUID id,
            UUID authEntryPointId,
            String ipAddress,
            String comment,
            Long createTime
    ) {
        this.id = id;
        this.authEntryPointId = authEntryPointId;
        this.ipAddress = ipAddress;
        this.comment = comment;
        this.createTime = createTime;
    }

    public UUID getId() {
        return this.id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public UUID getAuthEntryPointId() {
        return this.authEntryPointId;
    }

    public void setAuthEntryPointId(UUID authEntryPointId) {
        this.authEntryPointId = authEntryPointId;
    }

    public String getIpAddress() {
        return this.ipAddress;
    }

    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public Long getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AuthSessionFailEntity other = (AuthSessionFailEntity) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        } else if (!id.equals(other.id))
            return false;
        if (authEntryPointId == null) {
            if (other.authEntryPointId != null)
                return false;
        } else if (!authEntryPointId.equals(other.authEntryPointId))
            return false;
        if (ipAddress == null) {
            if (other.ipAddress != null)
                return false;
        } else if (!ipAddress.equals(other.ipAddress))
            return false;
        if (comment == null) {
            if (other.comment != null)
                return false;
        } else if (!comment.equals(other.comment))
            return false;
        if (createTime == null) {
            if (other.createTime != null)
                return false;
        } else if (!createTime.equals(other.createTime))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((id == null) ? 0 : id.hashCode());
        result = prime * result + ((authEntryPointId == null) ? 0 : authEntryPointId.hashCode());
        result = prime * result + ((ipAddress == null) ? 0 : ipAddress.hashCode());
        result = prime * result + ((comment == null) ? 0 : comment.hashCode());
        result = prime * result + ((createTime == null) ? 0 : createTime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AuthSessionFailEntity (");

        sb.append(id);
        sb.append(", ").append(authEntryPointId);
        sb.append(", ").append(ipAddress);
        sb.append(", ").append(comment);
        sb.append(", ").append(createTime);

        sb.append(")");
        return sb.toString();
    }
}
