/*
 * This file is generated by jOOQ.
*/
package com.zemrow.test.dsl.jooq.autogen.auth.dao.entity;


import com.zemrow.test.dsl.jooq.impl.AbstractEntity;

import java.io.Serializable;
import java.util.UUID;


/**
 * Способы авторизации пользователя
 */
public class AuthEntryPointEntity extends AbstractEntity implements Serializable {

    private static final long serialVersionUID = -458495279;

    /**
     * ID пользователя
     */
    private UUID authUserId;
    /**
     * Способ(система) авторизации: логин_пароль, vk.com, google, ...
     */
    private String entryPointType;
    /**
     * Идентификатор в системе авторизации (логин)
     */
    private String clientId;
    /**
     * Удостоверение личности в системе авторизации (пароль)
     */
    private String credential;
    /**
     * Прошел ли подтверждени
     */
    private Boolean validate;
    /**
     * Дата создания записи
     */
    private Long createTime;
    /**
     * Пользователь создавший запись
     */
    private UUID createdBy;
    /**
     * Дата обновления записи
     */
    private Long updateTime;
    /**
     * Пользователь обновивший запись
     */
    private UUID updatedBy;
    /**
     * Дата удаления записи
     */
    private Long deleteTime;
    /**
     * Пользователь удаливший запись
     */
    private UUID deletedBy;

    public AuthEntryPointEntity() {
    }

    public AuthEntryPointEntity(AuthEntryPointEntity value) {
        super(value);
        this.authUserId = value.authUserId;
        this.entryPointType = value.entryPointType;
        this.clientId = value.clientId;
        this.credential = value.credential;
        this.validate = value.validate;
        this.createTime = value.createTime;
        this.createdBy = value.createdBy;
        this.updateTime = value.updateTime;
        this.updatedBy = value.updatedBy;
        this.deleteTime = value.deleteTime;
        this.deletedBy = value.deletedBy;
    }

    public AuthEntryPointEntity(
            UUID id,
            UUID authUserId,
            String entryPointType,
            String clientId,
            String credential,
            Boolean validate,
            Long createTime,
            UUID createdBy,
            Long updateTime,
            UUID updatedBy,
            Long deleteTime,
            UUID deletedBy
    ) {
        super(id);
        this.authUserId = authUserId;
        this.entryPointType = entryPointType;
        this.clientId = clientId;
        this.credential = credential;
        this.validate = validate;
        this.createTime = createTime;
        this.createdBy = createdBy;
        this.updateTime = updateTime;
        this.updatedBy = updatedBy;
        this.deleteTime = deleteTime;
        this.deletedBy = deletedBy;
    }

    public UUID getAuthUserId() {
        return this.authUserId;
    }

    public void setAuthUserId(UUID authUserId) {
        this.authUserId = authUserId;
    }

    public String getEntryPointType() {
        return this.entryPointType;
    }

    public void setEntryPointType(String entryPointType) {
        this.entryPointType = entryPointType;
    }

    public String getClientId() {
        return this.clientId;
    }

    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    public String getCredential() {
        return this.credential;
    }

    public void setCredential(String credential) {
        this.credential = credential;
    }

    public Boolean getValidate() {
        return this.validate;
    }

    public void setValidate(Boolean validate) {
        this.validate = validate;
    }

    public Long getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public UUID getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(UUID createdBy) {
        this.createdBy = createdBy;
    }

    public Long getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    public UUID getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(UUID updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Long getDeleteTime() {
        return this.deleteTime;
    }

    public void setDeleteTime(Long deleteTime) {
        this.deleteTime = deleteTime;
    }

    public UUID getDeletedBy() {
        return this.deletedBy;
    }

    public void setDeletedBy(UUID deletedBy) {
        this.deletedBy = deletedBy;
    }

    @Override
    public String toString() {
        final StringBuilder sb = new StringBuilder("AuthEntryPointEntity (");

        sb.append("id:").append(id);
        sb.append(", authUserId:").append(authUserId);
        sb.append(", entryPointType:").append(entryPointType);
        sb.append(", clientId:").append(clientId);
        sb.append(", credential:").append(credential);
        sb.append(", validate:").append(validate);
        sb.append(", createTime:").append(createTime);
        sb.append(", createdBy:").append(createdBy);
        sb.append(", updateTime:").append(updateTime);
        sb.append(", updatedBy:").append(updatedBy);
        sb.append(", deleteTime:").append(deleteTime);
        sb.append(", deletedBy:").append(deletedBy);

        sb.append(")");
        return sb.toString();
    }

    @Override
    public boolean equals(Object obj) {
        if (!super.equals(obj)) {
            return false;
        }
        if (!(obj instanceof AuthEntryPointEntity)) {
            return false;
        }
        final AuthEntryPointEntity other = (AuthEntryPointEntity) obj;
        if (authUserId == null) {
            if (other.authUserId != null) {
                return false;
            }
        } else if (!authUserId.equals(other.authUserId)) {
            return false;
        }
        if (entryPointType == null) {
            if (other.entryPointType != null) {
                return false;
            }
        } else if (!entryPointType.equals(other.entryPointType)) {
            return false;
        }
        if (clientId == null) {
            if (other.clientId != null) {
                return false;
            }
        } else if (!clientId.equals(other.clientId)) {
            return false;
        }
        if (credential == null) {
            if (other.credential != null) {
                return false;
            }
        } else if (!credential.equals(other.credential)) {
            return false;
        }
        if (validate == null) {
            if (other.validate != null) {
                return false;
            }
        } else if (!validate.equals(other.validate)) {
            return false;
        }
        if (createTime == null) {
            if (other.createTime != null) {
                return false;
            }
        } else if (!createTime.equals(other.createTime)) {
            return false;
        }
        if (createdBy == null) {
            if (other.createdBy != null) {
                return false;
            }
        } else if (!createdBy.equals(other.createdBy)) {
            return false;
        }
        if (updateTime == null) {
            if (other.updateTime != null) {
                return false;
            }
        } else if (!updateTime.equals(other.updateTime)) {
            return false;
        }
        if (updatedBy == null) {
            if (other.updatedBy != null) {
                return false;
            }
        } else if (!updatedBy.equals(other.updatedBy)) {
            return false;
        }
        if (deleteTime == null) {
            if (other.deleteTime != null) {
                return false;
            }
        } else if (!deleteTime.equals(other.deleteTime)) {
            return false;
        }
        if (deletedBy == null) {
            if (other.deletedBy != null) {
                return false;
            }
        } else if (!deletedBy.equals(other.deletedBy)) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int result = super.hashCode();
        result = 31 * result + ((authUserId == null) ? 0 : authUserId.hashCode());
        result = 31 * result + ((entryPointType == null) ? 0 : entryPointType.hashCode());
        result = 31 * result + ((clientId == null) ? 0 : clientId.hashCode());
        result = 31 * result + ((credential == null) ? 0 : credential.hashCode());
        result = 31 * result + ((validate == null) ? 0 : validate.hashCode());
        result = 31 * result + ((createTime == null) ? 0 : createTime.hashCode());
        result = 31 * result + ((createdBy == null) ? 0 : createdBy.hashCode());
        result = 31 * result + ((updateTime == null) ? 0 : updateTime.hashCode());
        result = 31 * result + ((updatedBy == null) ? 0 : updatedBy.hashCode());
        result = 31 * result + ((deleteTime == null) ? 0 : deleteTime.hashCode());
        result = 31 * result + ((deletedBy == null) ? 0 : deletedBy.hashCode());
        return result;
    }
}
