/*
 * This file is generated by jOOQ.
*/
package com.zemrow.test.dsl.jooq.autogen.auth.dao.entity;


import java.io.Serializable;
import java.util.UUID;


/**
 * Сессия пользователя
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class AuthSessionEntity implements Serializable {

    private static final long serialVersionUID = 1440107140;

    private UUID id;
    private UUID authEntryPointId;
    private String token;
    private Long createTime;
    private Long deleteTime;
    private UUID deletedBy;

    public AuthSessionEntity() {
    }

    public AuthSessionEntity(AuthSessionEntity value) {
        this.id = value.id;
        this.authEntryPointId = value.authEntryPointId;
        this.token = value.token;
        this.createTime = value.createTime;
        this.deleteTime = value.deleteTime;
        this.deletedBy = value.deletedBy;
    }

    public AuthSessionEntity(
            UUID id,
            UUID authEntryPointId,
            String token,
            Long createTime,
            Long deleteTime,
            UUID deletedBy
    ) {
        this.id = id;
        this.authEntryPointId = authEntryPointId;
        this.token = token;
        this.createTime = createTime;
        this.deleteTime = deleteTime;
        this.deletedBy = deletedBy;
    }

    public UUID getId() {
        return this.id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public UUID getAuthEntryPointId() {
        return this.authEntryPointId;
    }

    public void setAuthEntryPointId(UUID authEntryPointId) {
        this.authEntryPointId = authEntryPointId;
    }

    public String getToken() {
        return this.token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public Long getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public Long getDeleteTime() {
        return this.deleteTime;
    }

    public void setDeleteTime(Long deleteTime) {
        this.deleteTime = deleteTime;
    }

    public UUID getDeletedBy() {
        return this.deletedBy;
    }

    public void setDeletedBy(UUID deletedBy) {
        this.deletedBy = deletedBy;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AuthSessionEntity other = (AuthSessionEntity) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        } else if (!id.equals(other.id))
            return false;
        if (authEntryPointId == null) {
            if (other.authEntryPointId != null)
                return false;
        } else if (!authEntryPointId.equals(other.authEntryPointId))
            return false;
        if (token == null) {
            if (other.token != null)
                return false;
        } else if (!token.equals(other.token))
            return false;
        if (createTime == null) {
            if (other.createTime != null)
                return false;
        } else if (!createTime.equals(other.createTime))
            return false;
        if (deleteTime == null) {
            if (other.deleteTime != null)
                return false;
        } else if (!deleteTime.equals(other.deleteTime))
            return false;
        if (deletedBy == null) {
            if (other.deletedBy != null)
                return false;
        } else if (!deletedBy.equals(other.deletedBy))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((id == null) ? 0 : id.hashCode());
        result = prime * result + ((authEntryPointId == null) ? 0 : authEntryPointId.hashCode());
        result = prime * result + ((token == null) ? 0 : token.hashCode());
        result = prime * result + ((createTime == null) ? 0 : createTime.hashCode());
        result = prime * result + ((deleteTime == null) ? 0 : deleteTime.hashCode());
        result = prime * result + ((deletedBy == null) ? 0 : deletedBy.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AuthSessionEntity (");

        sb.append(id);
        sb.append(", ").append(authEntryPointId);
        sb.append(", ").append(token);
        sb.append(", ").append(createTime);
        sb.append(", ").append(deleteTime);
        sb.append(", ").append(deletedBy);

        sb.append(")");
        return sb.toString();
    }
}
