/*
 * This file is generated by jOOQ.
*/
package com.zemrow.test.dsl.jooq.autogen.log.dao.entity;


import java.io.Serializable;
import java.util.UUID;


/**
 * Логи вызовов сервисов
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class RoutLogEntity implements Serializable {

    private static final long serialVersionUID = -70578082;

    private UUID id;
    private String token;
    private String serviceId;
    private String action;
    private Long startInvoke;
    private Long endInvoke;
    private String errorStackTrace;

    public RoutLogEntity() {
    }

    public RoutLogEntity(RoutLogEntity value) {
        this.id = value.id;
        this.token = value.token;
        this.serviceId = value.serviceId;
        this.action = value.action;
        this.startInvoke = value.startInvoke;
        this.endInvoke = value.endInvoke;
        this.errorStackTrace = value.errorStackTrace;
    }

    public RoutLogEntity(
            UUID id,
            String token,
            String serviceId,
            String action,
            Long startInvoke,
            Long endInvoke,
            String errorStackTrace
    ) {
        this.id = id;
        this.token = token;
        this.serviceId = serviceId;
        this.action = action;
        this.startInvoke = startInvoke;
        this.endInvoke = endInvoke;
        this.errorStackTrace = errorStackTrace;
    }

    public UUID getId() {
        return this.id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public String getToken() {
        return this.token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getServiceId() {
        return this.serviceId;
    }

    public void setServiceId(String serviceId) {
        this.serviceId = serviceId;
    }

    public String getAction() {
        return this.action;
    }

    public void setAction(String action) {
        this.action = action;
    }

    public Long getStartInvoke() {
        return this.startInvoke;
    }

    public void setStartInvoke(Long startInvoke) {
        this.startInvoke = startInvoke;
    }

    public Long getEndInvoke() {
        return this.endInvoke;
    }

    public void setEndInvoke(Long endInvoke) {
        this.endInvoke = endInvoke;
    }

    public String getErrorStackTrace() {
        return this.errorStackTrace;
    }

    public void setErrorStackTrace(String errorStackTrace) {
        this.errorStackTrace = errorStackTrace;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final RoutLogEntity other = (RoutLogEntity) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        } else if (!id.equals(other.id))
            return false;
        if (token == null) {
            if (other.token != null)
                return false;
        } else if (!token.equals(other.token))
            return false;
        if (serviceId == null) {
            if (other.serviceId != null)
                return false;
        } else if (!serviceId.equals(other.serviceId))
            return false;
        if (action == null) {
            if (other.action != null)
                return false;
        } else if (!action.equals(other.action))
            return false;
        if (startInvoke == null) {
            if (other.startInvoke != null)
                return false;
        } else if (!startInvoke.equals(other.startInvoke))
            return false;
        if (endInvoke == null) {
            if (other.endInvoke != null)
                return false;
        } else if (!endInvoke.equals(other.endInvoke))
            return false;
        if (errorStackTrace == null) {
            if (other.errorStackTrace != null)
                return false;
        } else if (!errorStackTrace.equals(other.errorStackTrace))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((id == null) ? 0 : id.hashCode());
        result = prime * result + ((token == null) ? 0 : token.hashCode());
        result = prime * result + ((serviceId == null) ? 0 : serviceId.hashCode());
        result = prime * result + ((action == null) ? 0 : action.hashCode());
        result = prime * result + ((startInvoke == null) ? 0 : startInvoke.hashCode());
        result = prime * result + ((endInvoke == null) ? 0 : endInvoke.hashCode());
        result = prime * result + ((errorStackTrace == null) ? 0 : errorStackTrace.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RoutLogEntity (");

        sb.append(id);
        sb.append(", ").append(token);
        sb.append(", ").append(serviceId);
        sb.append(", ").append(action);
        sb.append(", ").append(startInvoke);
        sb.append(", ").append(endInvoke);
        sb.append(", ").append(errorStackTrace);

        sb.append(")");
        return sb.toString();
    }
}
