/*
 * This file is generated by jOOQ.
*/
package com.zemrow.test.dsl.jooq.autogen.tables.records;


import com.zemrow.test.dsl.jooq.autogen.tables.AuthSessionFail;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.util.UUID;


/**
 * Неудачные попытки войти в систему
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.0"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class AuthSessionFailRecord extends UpdatableRecordImpl<AuthSessionFailRecord> implements Record5<UUID, UUID, String, String, Long> {

    private static final long serialVersionUID = 1186366981;

    /**
     * Setter for <code>auth.auth_session_fail.id</code>. ID записи
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>auth.auth_session_fail.id</code>. ID записи
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>auth.auth_session_fail.auth_entry_point_id</code>. Точка входа пользователя
     */
    public void setAuthEntryPointId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>auth.auth_session_fail.auth_entry_point_id</code>. Точка входа пользователя
     */
    public UUID getAuthEntryPointId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>auth.auth_session_fail.ip_address</code>. IP адрес клиента
     */
    public void setIpAddress(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>auth.auth_session_fail.ip_address</code>. IP адрес клиента
     */
    public String getIpAddress() {
        return (String) get(2);
    }

    /**
     * Setter for <code>auth.auth_session_fail.comment</code>. Сообщение об ошибке
     */
    public void setComment(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>auth.auth_session_fail.comment</code>. Сообщение об ошибке
     */
    public String getComment() {
        return (String) get(3);
    }

    /**
     * Setter for <code>auth.auth_session_fail.create_time</code>. Дата создания записи
     */
    public void setCreateTime(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>auth.auth_session_fail.create_time</code>. Дата создания записи
     */
    public Long getCreateTime() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UUID, UUID, String, String, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UUID, UUID, String, String, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field1() {
        return AuthSessionFail.AUTH_SESSION_FAIL.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field2() {
        return AuthSessionFail.AUTH_SESSION_FAIL.AUTH_ENTRY_POINT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return AuthSessionFail.AUTH_SESSION_FAIL.IP_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return AuthSessionFail.AUTH_SESSION_FAIL.COMMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return AuthSessionFail.AUTH_SESSION_FAIL.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value2() {
        return getAuthEntryPointId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getIpAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getComment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthSessionFailRecord value1(UUID value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthSessionFailRecord value2(UUID value) {
        setAuthEntryPointId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthSessionFailRecord value3(String value) {
        setIpAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthSessionFailRecord value4(String value) {
        setComment(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthSessionFailRecord value5(Long value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthSessionFailRecord values(UUID value1, UUID value2, String value3, String value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuthSessionFailRecord
     */
    public AuthSessionFailRecord() {
        super(AuthSessionFail.AUTH_SESSION_FAIL);
    }

    /**
     * Create a detached, initialised AuthSessionFailRecord
     */
    public AuthSessionFailRecord(UUID id, UUID authEntryPointId, String ipAddress, String comment, Long createTime) {
        super(AuthSessionFail.AUTH_SESSION_FAIL);

        set(0, id);
        set(1, authEntryPointId);
        set(2, ipAddress);
        set(3, comment);
        set(4, createTime);
    }
}
