/*
 * This file is generated by jOOQ.
*/
package com.zemrow.test.dsl.jooq.autogen.tables.records;


import com.zemrow.test.dsl.jooq.autogen.tables.AuthEntryPoint;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.util.UUID;


/**
 * Способы авторизации пользователя
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.0"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class AuthEntryPointRecord extends UpdatableRecordImpl<AuthEntryPointRecord> implements Record12<UUID, UUID, String, String, String, Boolean, Long, UUID, Long, UUID, Long, UUID> {

    private static final long serialVersionUID = 1182099927;

    /**
     * Setter for <code>auth.auth_entry_point.id</code>. ID записи
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>auth.auth_entry_point.id</code>. ID записи
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>auth.auth_entry_point.auth_user_id</code>. ID пользователя
     */
    public void setAuthUserId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>auth.auth_entry_point.auth_user_id</code>. ID пользователя
     */
    public UUID getAuthUserId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>auth.auth_entry_point.entry_point_type</code>. Способ(система) авторизации: логин_пароль, vk.com, google, ...
     */
    public void setEntryPointType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>auth.auth_entry_point.entry_point_type</code>. Способ(система) авторизации: логин_пароль, vk.com, google, ...
     */
    public String getEntryPointType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>auth.auth_entry_point.client_id</code>. Идентификатор в системе авторизации (логин)
     */
    public void setClientId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>auth.auth_entry_point.client_id</code>. Идентификатор в системе авторизации (логин)
     */
    public String getClientId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>auth.auth_entry_point.credential</code>. Удостоверение личности в системе авторизации (пароль)
     */
    public void setCredential(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>auth.auth_entry_point.credential</code>. Удостоверение личности в системе авторизации (пароль)
     */
    public String getCredential() {
        return (String) get(4);
    }

    /**
     * Setter for <code>auth.auth_entry_point.validate</code>. Прошел ли подтверждени
     */
    public void setValidate(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>auth.auth_entry_point.validate</code>. Прошел ли подтверждени
     */
    public Boolean getValidate() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>auth.auth_entry_point.create_time</code>. Дата создания записи
     */
    public void setCreateTime(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>auth.auth_entry_point.create_time</code>. Дата создания записи
     */
    public Long getCreateTime() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>auth.auth_entry_point.created_by</code>. Пользователь создавший запись
     */
    public void setCreatedBy(UUID value) {
        set(7, value);
    }

    /**
     * Getter for <code>auth.auth_entry_point.created_by</code>. Пользователь создавший запись
     */
    public UUID getCreatedBy() {
        return (UUID) get(7);
    }

    /**
     * Setter for <code>auth.auth_entry_point.update_time</code>. Дата обновления записи
     */
    public void setUpdateTime(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>auth.auth_entry_point.update_time</code>. Дата обновления записи
     */
    public Long getUpdateTime() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>auth.auth_entry_point.updated_by</code>. Пользователь обновивший запись
     */
    public void setUpdatedBy(UUID value) {
        set(9, value);
    }

    /**
     * Getter for <code>auth.auth_entry_point.updated_by</code>. Пользователь обновивший запись
     */
    public UUID getUpdatedBy() {
        return (UUID) get(9);
    }

    /**
     * Setter for <code>auth.auth_entry_point.delete_time</code>. Дата удаления записи
     */
    public void setDeleteTime(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>auth.auth_entry_point.delete_time</code>. Дата удаления записи
     */
    public Long getDeleteTime() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>auth.auth_entry_point.deleted_by</code>. Пользователь удаливший запись
     */
    public void setDeletedBy(UUID value) {
        set(11, value);
    }

    /**
     * Getter for <code>auth.auth_entry_point.deleted_by</code>. Пользователь удаливший запись
     */
    public UUID getDeletedBy() {
        return (UUID) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<UUID, UUID, String, String, String, Boolean, Long, UUID, Long, UUID, Long, UUID> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<UUID, UUID, String, String, String, Boolean, Long, UUID, Long, UUID, Long, UUID> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field1() {
        return AuthEntryPoint.AUTH_ENTRY_POINT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field2() {
        return AuthEntryPoint.AUTH_ENTRY_POINT.AUTH_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return AuthEntryPoint.AUTH_ENTRY_POINT.ENTRY_POINT_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return AuthEntryPoint.AUTH_ENTRY_POINT.CLIENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return AuthEntryPoint.AUTH_ENTRY_POINT.CREDENTIAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return AuthEntryPoint.AUTH_ENTRY_POINT.VALIDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return AuthEntryPoint.AUTH_ENTRY_POINT.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field8() {
        return AuthEntryPoint.AUTH_ENTRY_POINT.CREATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return AuthEntryPoint.AUTH_ENTRY_POINT.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field10() {
        return AuthEntryPoint.AUTH_ENTRY_POINT.UPDATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field11() {
        return AuthEntryPoint.AUTH_ENTRY_POINT.DELETE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field12() {
        return AuthEntryPoint.AUTH_ENTRY_POINT.DELETED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value2() {
        return getAuthUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getEntryPointType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getClientId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCredential();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getValidate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value8() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value10() {
        return getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value11() {
        return getDeleteTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value12() {
        return getDeletedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthEntryPointRecord value1(UUID value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthEntryPointRecord value2(UUID value) {
        setAuthUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthEntryPointRecord value3(String value) {
        setEntryPointType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthEntryPointRecord value4(String value) {
        setClientId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthEntryPointRecord value5(String value) {
        setCredential(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthEntryPointRecord value6(Boolean value) {
        setValidate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthEntryPointRecord value7(Long value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthEntryPointRecord value8(UUID value) {
        setCreatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthEntryPointRecord value9(Long value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthEntryPointRecord value10(UUID value) {
        setUpdatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthEntryPointRecord value11(Long value) {
        setDeleteTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthEntryPointRecord value12(UUID value) {
        setDeletedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthEntryPointRecord values(UUID value1, UUID value2, String value3, String value4, String value5, Boolean value6, Long value7, UUID value8, Long value9, UUID value10, Long value11, UUID value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuthEntryPointRecord
     */
    public AuthEntryPointRecord() {
        super(AuthEntryPoint.AUTH_ENTRY_POINT);
    }

    /**
     * Create a detached, initialised AuthEntryPointRecord
     */
    public AuthEntryPointRecord(UUID id, UUID authUserId, String entryPointType, String clientId, String credential, Boolean validate, Long createTime, UUID createdBy, Long updateTime, UUID updatedBy, Long deleteTime, UUID deletedBy) {
        super(AuthEntryPoint.AUTH_ENTRY_POINT);

        set(0, id);
        set(1, authUserId);
        set(2, entryPointType);
        set(3, clientId);
        set(4, credential);
        set(5, validate);
        set(6, createTime);
        set(7, createdBy);
        set(8, updateTime);
        set(9, updatedBy);
        set(10, deleteTime);
        set(11, deletedBy);
    }
}
