/*
 * This file is generated by jOOQ.
*/
package com.zemrow.test.dsl.jooq.autogen.log.dao.constants;


import com.zemrow.test.dsl.jooq.autogen.log.SchemaLogConst;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import java.util.UUID;


/**
 * Логи вызовов сервисов
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class RoutLogConst extends TableImpl<Record> {

    private static final long serialVersionUID = -2103784957;

    /**
     * The reference instance of <code>log.rout_log</code>
     */
    public static final RoutLogConst ROUT_LOG = new RoutLogConst();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>log.rout_log.id</code>. ID записи
     */
    public final TableField<Record, UUID> ID = createField("id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "ID записи");

    /**
     * The column <code>log.rout_log.token</code>. Уникальный идентификатор сессии пользователя
     */
    public final TableField<Record, String> TOKEN = createField("token", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "Уникальный идентификатор сессии пользователя");

    /**
     * The column <code>log.rout_log.service_id</code>. Идентификатор сервиса
     */
    public final TableField<Record, String> SERVICE_ID = createField("service_id", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "Идентификатор сервиса");

    /**
     * The column <code>log.rout_log.action</code>. Имя метода
     */
    public final TableField<Record, String> ACTION = createField("action", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "Имя метода");

    /**
     * The column <code>log.rout_log.start_invoke</code>. Время запуска
     */
    public final TableField<Record, Long> START_INVOKE = createField("start_invoke", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "Время запуска");

    /**
     * The column <code>log.rout_log.end_invoke</code>. Время окончания
     */
    public final TableField<Record, Long> END_INVOKE = createField("end_invoke", org.jooq.impl.SQLDataType.BIGINT, this, "Время окончания");

    /**
     * The column <code>log.rout_log.error_stack_trace</code>. Ошибка если была (stacktrace)
     */
    public final TableField<Record, String> ERROR_STACK_TRACE = createField("error_stack_trace", org.jooq.impl.SQLDataType.CLOB, this, "Ошибка если была (stacktrace)");

    /**
     * Create a <code>log.rout_log</code> table reference
     */
    public RoutLogConst() {
        this("rout_log", null);
    }

    /**
     * Create an aliased <code>log.rout_log</code> table reference
     */
    public RoutLogConst(String alias) {
        this(alias, ROUT_LOG);
    }

    private RoutLogConst(String alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private RoutLogConst(String alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "Логи вызовов сервисов");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return SchemaLogConst.LOG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoutLogConst as(String alias) {
        return new RoutLogConst(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RoutLogConst rename(String name) {
        return new RoutLogConst(name, null);
    }
}
