/*
 * This file is generated by jOOQ.
*/
package com.zemrow.test.dsl.jooq.autogen;


import com.zemrow.test.dsl.jooq.autogen.tables.AuthEntryPoint;
import com.zemrow.test.dsl.jooq.autogen.tables.AuthSession;
import com.zemrow.test.dsl.jooq.autogen.tables.AuthSessionFail;
import com.zemrow.test.dsl.jooq.autogen.tables.AuthUser;
import com.zemrow.test.dsl.jooq.autogen.tables.records.AuthEntryPointRecord;
import com.zemrow.test.dsl.jooq.autogen.tables.records.AuthSessionFailRecord;
import com.zemrow.test.dsl.jooq.autogen.tables.records.AuthSessionRecord;
import com.zemrow.test.dsl.jooq.autogen.tables.records.AuthUserRecord;
import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;

import javax.annotation.Generated;


/**
 * A class modelling foreign key relationships between tables of the <code>auth</code>
 * schema
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.0"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AuthEntryPointRecord> PK_AUTH_ENTRY_POINT = UniqueKeys0.PK_AUTH_ENTRY_POINT;
    public static final UniqueKey<AuthEntryPointRecord> AUTH_ENTRY_POINT_ENTRY_POINT_TYPE_CLIENT_ID_KEY = UniqueKeys0.AUTH_ENTRY_POINT_ENTRY_POINT_TYPE_CLIENT_ID_KEY;
    public static final UniqueKey<AuthSessionRecord> PK_AUTH_SESSION = UniqueKeys0.PK_AUTH_SESSION;
    public static final UniqueKey<AuthSessionFailRecord> PK_AUTH_SESSION_FAIL = UniqueKeys0.PK_AUTH_SESSION_FAIL;
    public static final UniqueKey<AuthUserRecord> PK_AUTH_USER = UniqueKeys0.PK_AUTH_USER;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AuthEntryPointRecord, AuthUserRecord> AUTH_ENTRY_POINT__AUTH_ENTRY_POINT__AUTH_USER_ID__FK = ForeignKeys0.AUTH_ENTRY_POINT__AUTH_ENTRY_POINT__AUTH_USER_ID__FK;
    public static final ForeignKey<AuthEntryPointRecord, AuthUserRecord> AUTH_ENTRY_POINT__AUTH_ENTRY_POINT__CREATED_BY__FK = ForeignKeys0.AUTH_ENTRY_POINT__AUTH_ENTRY_POINT__CREATED_BY__FK;
    public static final ForeignKey<AuthEntryPointRecord, AuthUserRecord> AUTH_ENTRY_POINT__AUTH_ENTRY_POINT__UPDATED_BY__FK = ForeignKeys0.AUTH_ENTRY_POINT__AUTH_ENTRY_POINT__UPDATED_BY__FK;
    public static final ForeignKey<AuthEntryPointRecord, AuthUserRecord> AUTH_ENTRY_POINT__AUTH_ENTRY_POINT__DELETED_BY__FK = ForeignKeys0.AUTH_ENTRY_POINT__AUTH_ENTRY_POINT__DELETED_BY__FK;
    public static final ForeignKey<AuthSessionRecord, AuthEntryPointRecord> AUTH_SESSION__AUTH_SESSION__AUTH_ENTRY_POINT_ID__FK = ForeignKeys0.AUTH_SESSION__AUTH_SESSION__AUTH_ENTRY_POINT_ID__FK;
    public static final ForeignKey<AuthSessionRecord, AuthUserRecord> AUTH_SESSION__AUTH_SESSION__DELETED_BY__FK = ForeignKeys0.AUTH_SESSION__AUTH_SESSION__DELETED_BY__FK;
    public static final ForeignKey<AuthSessionFailRecord, AuthEntryPointRecord> AUTH_SESSION_FAIL__AUTH_SESSION_FAIL__AUTH_ENTRY_POINT_ID__FK = ForeignKeys0.AUTH_SESSION_FAIL__AUTH_SESSION_FAIL__AUTH_ENTRY_POINT_ID__FK;
    public static final ForeignKey<AuthUserRecord, AuthUserRecord> AUTH_USER__AUTH_USER__CREATED_BY__FK = ForeignKeys0.AUTH_USER__AUTH_USER__CREATED_BY__FK;
    public static final ForeignKey<AuthUserRecord, AuthUserRecord> AUTH_USER__AUTH_USER__UPDATED_BY__FK = ForeignKeys0.AUTH_USER__AUTH_USER__UPDATED_BY__FK;
    public static final ForeignKey<AuthUserRecord, AuthUserRecord> AUTH_USER__AUTH_USER__DELETED_BY__FK = ForeignKeys0.AUTH_USER__AUTH_USER__DELETED_BY__FK;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<AuthEntryPointRecord> PK_AUTH_ENTRY_POINT = createUniqueKey(AuthEntryPoint.AUTH_ENTRY_POINT, "pk_auth_entry_point", AuthEntryPoint.AUTH_ENTRY_POINT.ID);
        public static final UniqueKey<AuthEntryPointRecord> AUTH_ENTRY_POINT_ENTRY_POINT_TYPE_CLIENT_ID_KEY = createUniqueKey(AuthEntryPoint.AUTH_ENTRY_POINT, "auth_entry_point_entry_point_type_client_id_key", AuthEntryPoint.AUTH_ENTRY_POINT.ENTRY_POINT_TYPE, AuthEntryPoint.AUTH_ENTRY_POINT.CLIENT_ID);
        public static final UniqueKey<AuthSessionRecord> PK_AUTH_SESSION = createUniqueKey(AuthSession.AUTH_SESSION, "pk_auth_session", AuthSession.AUTH_SESSION.ID);
        public static final UniqueKey<AuthSessionFailRecord> PK_AUTH_SESSION_FAIL = createUniqueKey(AuthSessionFail.AUTH_SESSION_FAIL, "pk_auth_session_fail", AuthSessionFail.AUTH_SESSION_FAIL.ID);
        public static final UniqueKey<AuthUserRecord> PK_AUTH_USER = createUniqueKey(AuthUser.AUTH_USER, "pk_auth_user", AuthUser.AUTH_USER.ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<AuthEntryPointRecord, AuthUserRecord> AUTH_ENTRY_POINT__AUTH_ENTRY_POINT__AUTH_USER_ID__FK = createForeignKey(com.zemrow.test.dsl.jooq.autogen.Keys.PK_AUTH_USER, AuthEntryPoint.AUTH_ENTRY_POINT, "auth_entry_point__auth_entry_point__auth_user_id__fk", AuthEntryPoint.AUTH_ENTRY_POINT.AUTH_USER_ID);
        public static final ForeignKey<AuthEntryPointRecord, AuthUserRecord> AUTH_ENTRY_POINT__AUTH_ENTRY_POINT__CREATED_BY__FK = createForeignKey(com.zemrow.test.dsl.jooq.autogen.Keys.PK_AUTH_USER, AuthEntryPoint.AUTH_ENTRY_POINT, "auth_entry_point__auth_entry_point__created_by__fk", AuthEntryPoint.AUTH_ENTRY_POINT.CREATED_BY);
        public static final ForeignKey<AuthEntryPointRecord, AuthUserRecord> AUTH_ENTRY_POINT__AUTH_ENTRY_POINT__UPDATED_BY__FK = createForeignKey(com.zemrow.test.dsl.jooq.autogen.Keys.PK_AUTH_USER, AuthEntryPoint.AUTH_ENTRY_POINT, "auth_entry_point__auth_entry_point__updated_by__fk", AuthEntryPoint.AUTH_ENTRY_POINT.UPDATED_BY);
        public static final ForeignKey<AuthEntryPointRecord, AuthUserRecord> AUTH_ENTRY_POINT__AUTH_ENTRY_POINT__DELETED_BY__FK = createForeignKey(com.zemrow.test.dsl.jooq.autogen.Keys.PK_AUTH_USER, AuthEntryPoint.AUTH_ENTRY_POINT, "auth_entry_point__auth_entry_point__deleted_by__fk", AuthEntryPoint.AUTH_ENTRY_POINT.DELETED_BY);
        public static final ForeignKey<AuthSessionRecord, AuthEntryPointRecord> AUTH_SESSION__AUTH_SESSION__AUTH_ENTRY_POINT_ID__FK = createForeignKey(com.zemrow.test.dsl.jooq.autogen.Keys.PK_AUTH_ENTRY_POINT, AuthSession.AUTH_SESSION, "auth_session__auth_session__auth_entry_point_id__fk", AuthSession.AUTH_SESSION.AUTH_ENTRY_POINT_ID);
        public static final ForeignKey<AuthSessionRecord, AuthUserRecord> AUTH_SESSION__AUTH_SESSION__DELETED_BY__FK = createForeignKey(com.zemrow.test.dsl.jooq.autogen.Keys.PK_AUTH_USER, AuthSession.AUTH_SESSION, "auth_session__auth_session__deleted_by__fk", AuthSession.AUTH_SESSION.DELETED_BY);
        public static final ForeignKey<AuthSessionFailRecord, AuthEntryPointRecord> AUTH_SESSION_FAIL__AUTH_SESSION_FAIL__AUTH_ENTRY_POINT_ID__FK = createForeignKey(com.zemrow.test.dsl.jooq.autogen.Keys.PK_AUTH_ENTRY_POINT, AuthSessionFail.AUTH_SESSION_FAIL, "auth_session_fail__auth_session_fail__auth_entry_point_id__fk", AuthSessionFail.AUTH_SESSION_FAIL.AUTH_ENTRY_POINT_ID);
        public static final ForeignKey<AuthUserRecord, AuthUserRecord> AUTH_USER__AUTH_USER__CREATED_BY__FK = createForeignKey(com.zemrow.test.dsl.jooq.autogen.Keys.PK_AUTH_USER, AuthUser.AUTH_USER, "auth_user__auth_user__created_by__fk", AuthUser.AUTH_USER.CREATED_BY);
        public static final ForeignKey<AuthUserRecord, AuthUserRecord> AUTH_USER__AUTH_USER__UPDATED_BY__FK = createForeignKey(com.zemrow.test.dsl.jooq.autogen.Keys.PK_AUTH_USER, AuthUser.AUTH_USER, "auth_user__auth_user__updated_by__fk", AuthUser.AUTH_USER.UPDATED_BY);
        public static final ForeignKey<AuthUserRecord, AuthUserRecord> AUTH_USER__AUTH_USER__DELETED_BY__FK = createForeignKey(com.zemrow.test.dsl.jooq.autogen.Keys.PK_AUTH_USER, AuthUser.AUTH_USER, "auth_user__auth_user__deleted_by__fk", AuthUser.AUTH_USER.DELETED_BY);
    }
}
