/*
 * This file is generated by jOOQ.
*/
package com.zemrow.test.dsl.jooq.autogen.auth.dao.constants;


import com.zemrow.test.dsl.jooq.autogen.auth.SchemaAuthConst;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import java.util.UUID;


/**
 * Сессия пользователя
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class AuthSessionConst extends TableImpl<Record> {

    private static final long serialVersionUID = -1795894036;

    /**
     * The reference instance of <code>auth.auth_session</code>
     */
    public static final AuthSessionConst AUTH_SESSION = new AuthSessionConst();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>auth.auth_session.id</code>. ID записи
     */
    public final TableField<Record, UUID> ID = createField("id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "ID записи");

    /**
     * The column <code>auth.auth_session.auth_entry_point_id</code>. Точка входа пользователя
     */
    public final TableField<Record, UUID> AUTH_ENTRY_POINT_ID = createField("auth_entry_point_id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "Точка входа пользователя");

    /**
     * The column <code>auth.auth_session.token</code>. Уникальный идентификатор сессии, сложный для подбора
     */
    public final TableField<Record, String> TOKEN = createField("token", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "Уникальный идентификатор сессии, сложный для подбора");

    /**
     * The column <code>auth.auth_session.create_time</code>. Дата создания записи
     */
    public final TableField<Record, Long> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "Дата создания записи");

    /**
     * The column <code>auth.auth_session.delete_time</code>. Дата удаления записи
     */
    public final TableField<Record, Long> DELETE_TIME = createField("delete_time", org.jooq.impl.SQLDataType.BIGINT, this, "Дата удаления записи");

    /**
     * The column <code>auth.auth_session.deleted_by</code>. Пользователь удаливший запись
     */
    public final TableField<Record, UUID> DELETED_BY = createField("deleted_by", org.jooq.impl.SQLDataType.UUID, this, "Пользователь удаливший запись");

    /**
     * Create a <code>auth.auth_session</code> table reference
     */
    public AuthSessionConst() {
        this("auth_session", null);
    }

    /**
     * Create an aliased <code>auth.auth_session</code> table reference
     */
    public AuthSessionConst(String alias) {
        this(alias, AUTH_SESSION);
    }

    private AuthSessionConst(String alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private AuthSessionConst(String alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "Сессия пользователя");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return SchemaAuthConst.AUTH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthSessionConst as(String alias) {
        return new AuthSessionConst(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthSessionConst rename(String name) {
        return new AuthSessionConst(name, null);
    }
}
